version: "3.9"

services:
  dapr-service:
    build:
      context: ./
    ports:
      - ${APP_SERVICE_HTTP_PORT:-80}:${APP_SERVICE_HTTP_PORT:-80}
    restart: unless-stopped
    env_file:
      - .env
